version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1
  aws-cli: circleci/aws-cli@3.1
  terraform: circleci/terraform@3.2

jobs:
  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup
      - terraform/install
      
      # Add ECR authentication steps
      - run:
          name: Login to ECR
          command: |
            echo "Logging in to ECR..."
            aws ecr get-login-password --region $AWS_REGION \
              | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Build and push Docker image with explicit region and registry
      - aws-ecr/build-and-push-image:
          repo: ${ECR_REPOSITORY}
          tag: 'latest'
          region: ${AWS_REGION}
          registry-id: AWS_ACCOUNT_ID
      
      # Initialize and apply Terraform
      - run:
          name: Terraform Init and Apply
          command: |
            terraform init
            terraform apply -auto-approve
      
      # Deploy with Ansible
      - run:
          name: Install Ansible
          command: |
            pip install ansible
            
      - run:
          name: Deploy with Ansible
          command: |
            ansible-playbook -i inventory.ini site.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main

commands:
  open-settings:
    description: "Open CircleCI settings"
    parameters:
      key:
        type: string
        description: "The key of the setting to open"
      value:
        type: string
        description: "The value of the setting to open"
    steps:
      - run:
          name: Open CircleCI Settings
          command: |
            echo "Opening CircleCI settings: ${key} = ${value}"
